name: Benchmark Quarkus

on:
  workflow_dispatch:

jobs:
  ab:
    runs-on: ubuntu-22.04
    env:
      GH: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Run Benchmarks
        run: |
          cd $GITHUB_WORKSPACE/benches/ab
          chmod +x ./bench-quarkus.sh ../../code/gradlew ./run-ab.sh
          ./bench-quarkus.sh

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-ab-quarkus-${{runner.os}}
          path: ${{ github.workspace }}/benches/ab/quarkus-results.log

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-ab-quarkus-virtual-${{runner.os}}
          path: ${{ github.workspace }}/benches/ab/quarkus-results-virtual.log
  jmeter:
    runs-on: ubuntu-22.04
    env:
      GH: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Setup-Jmeter
        run: |
          sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          sudo tar -xvf apache-jmeter-5.6.3.tgz

      - name: Run Benchmarks
        run: |
          export PATH=$GITHUB_WORKSPACE/apache-jmeter-5.6.3/bin:$PATH
          cd $GITHUB_WORKSPACE/benches/jmeter
          chmod +x ./bench-quarkus.sh ../../code/gradlew ./run-jmeter.sh
          ./bench-quarkus.sh

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-jmeter-quarkus-${{runner.os}}
          path: ${{ github.workspace }}/benches/jmeter/quarkus-results.log

      - name: Upload result artifacts
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-jmeter-quarkus-virtual-${{runner.os}}
          path: ${{ github.workspace }}/benches/jmeter/quarkus-results-virtual.log

